[package]
name = "jsonrtl-cli"
description = "Command-line boundary for jsonrtl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
jsonrtl = { path = "../jsonrtl" }
jsonrtl-profiles = { path = "../jsonrtl-profiles" }
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "jsonrtl"
path = "src/main.rs"
